version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:erbium-browsers
  
    working_directory: ~/ci-test
  steps:
        - checkout
        
        - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        
        - run: npm install
    
        - save_cache:
          paths:
            - node_modules
            - ~/.npm 
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      
        - run: npm test